### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Mikeost** [Mikeost/github-profile-explorer#1]
## Todo list:
- [ ] Increasing primary rate limit ([auth, access token](https://docs.github.com/en/rest/authentication/authenticating-to-the-rest-api/)).
- [ ] Create/update/delete repositories ([OAuth](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/authorizing-oauth-apps/)).
- [ ] Filesystem operations (save logs, org/user info).
- [ ] Mock HTTP Response tests
- [x] [Redesign](https://docs.rs/ratatui/latest/ratatui/) (eaec267).
